# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# FGDB_Model_to_Code.py
# Created on: 2017-10-09 12:40:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
MyTest_gdb = "C:\\PyGEOGCoastal\\TestModeltoCode\\MyTest.gdb"
Data = "C:\\PyGEOGCoastal\\TestModeltoCode\\MyTest.gdb\\Data"
habTest = "C:\\PyGEOGCoastal\\TestModeltoCode\\MyTest.gdb\\Data\\habTest"

