# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MODEL_CLKR_CORRID2000.py
# Created on: 2017-06-06 12:05:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
WV_Rivers = "Hydrology\\WV_Rivers"
HUC4Watersheds = "HUC4Watersheds"
Clk_Riv_WS = "C:\\University of Washington GIS\\UOWSummer2017\\GEOG565\\Models\\TModel1_Scratch.gdb\\Hydrology\\Clk_River_WS"
Clk_RWS_Rivers = "C:\\University of Washington GIS\\UOWSummer2017\\GEOG565\\Models\\TModel1_Scratch.gdb\\Hydrology\\Clk_RWS_Rivers"
Clk_RWS_Rivers_Corridors2000 = "C:\\University of Washington GIS\\UOWSummer2017\\GEOG565\\Models\\TModel1_Scratch.gdb\\Hydrology\\Clk_RWS_RiverCorrid2000"

# Process: Select
arcpy.Select_analysis(HUC4Watersheds, Clk_Riv_WS, "Name = 'Clackamas'")

# Process: Clip
arcpy.Clip_analysis(WV_Rivers, Clk_Riv_WS, Clk_RWS_Rivers, "")

# Process: Buffer
arcpy.Buffer_analysis(Clk_RWS_Rivers, Clk_RWS_Rivers_Corridors2000, "1000 Feet", "FULL", "ROUND", "NONE", "", "PLANAR")

